PREFIX act: <http://example.org/activities/> 
PREFIX ex: <http://ns.inria.fr/sparql-micro-service/api#>
PREFIX schema: <http://schema.org/>

SELECT ?name ?country ?id (GROUP_CONCAT(?type; SEPARATOR=",") AS ?types) ?latitude ?longitude ?rating ?open_now
WHERE {
 ?x schema:name ?name;
      schema:country ?country.

BIND(IRI(CONCAT("http://localhost/service/roadtrip/getInformation?place=",?name)) as ?serviceURI)

SERVICE ?serviceURI{
  ?s ex:place_id ?id.
  OPTIONAL{ ?s ex:geometry ?geom.}
  OPTIONAL{?geom ex:location ?location.}
  OPTIONAL{?location ex:lat ?latitude;}
  OPTIONAL{?location ex:lng ?longitude.}
  OPTIONAL{ ?s ex:rating ?rating. }
  OPTIONAL{ ?s ex:opening_hours ?openH.}
  OPTIONAL{?openH ex:open_now ?open_now.}
  OPTIONAL{?s ex:types ?type.}
  }
}
GROUP BY ?name
