PREFIX act: <http://example.org/activities/> 
PREFIX ex: <http://ns.inria.fr/sparql-micro-service/api#>
PREFIX schema: <http://schema.org/>

SELECT ?name ?country (GROUP_CONCAT(?type; SEPARATOR=",") AS ?types) ?id ?latitude ?longitude ?rating ?open_now
WHERE {
 ?x schema:name ?name;
      schema:country ?country.
 BIND (str(?name as ?placeName)
SERVICE <http://localhost/service/roadtrip/getInformation?place=?placeName>{
        ?s ex:geometry ?geom.
        ?geom ex:location ?location.
        ?location ex:lat ?latitude;
                  ex:lng ?longitude.
        ?s ex:place_id ?id.
        ?s ex:rating ?rating. 
        ?s ex:types ?type.
        ?s ex:opening_hours ?openH.
        ?openH ex:open_now ?open_now.

  }
}