PREFIX act: <http://example.org/roadtrip/activity#> 
PREFIX schema: <http://example.org/roadtrip#>
PREFIX country: <http://example.org/roadtrip#>




SELECT ?address ?activities
WHERE {
  ?activities a schema:Activity;
    schema:hasCountry ?country. 
  ?country schema:hasCountryName ?y.
?activities schema:hasLocation ?location.
?location schema:hasAddress ?address
    filter(?y="France")

  }
 

#SELECT ?y (count(?activities) as ?counting)
# WHERE {
#   ?activities a schema:Activity;
#     schema:hasCountry ?y
#   }
# group by (?y)

# PREFIX act: <http://example.org/roadtrip/activity#> 
# PREFIX schema: <http://example.org/roadtrip#>
# PREFIX country: <http://example.org/roadtrip#>

# SELECT distinct ?activityname ?address 
#  WHERE {
#    ?activities a schema:UrbanActivity;
#      schema:hasCountry ?country.
# ?country schema:hasCountryName ?countryName.
# ?activities schema:hasLocation ?location;
#  schema:hasActivityName ?activityname
# ?location schema:hasAddress ?address. 

# filter(?countryName="United States")

#    }
